### ISSUE TITLE
Is the full list of medically-relevant genes available? 

### ISSUE THREAD

**Issue by danledinh** [UK-SBCoA-EbbertLab/brain_cDNA_discovery#2]
Is the full list of medically-relevant genes available? 

Based on your manuscript, the authors combined several lists of medically-relevant genes. However, I was not able to find this combined list of genes in this repo in supplemental materials.

**Comment by bernardo-heberle** [comment]
Yes, it is available on the Zenodo repository: https://zenodo.org/records/8180677

You can click this link to directly download the zip file that contains the medically-relevant gene annotation: https://zenodo.org/records/8180677/files/reproducing_RNA_figures.zip?download=1

Once you unzip the directory, the file you are looking for is named: `medically_relevant_genes.tsv`. There is also an informative `README.txt` file in there that describes the contents in each file.

Let me know if you run into any issues getting to the file and thank you for the interest in our work!
